### PR TITLE
Initial structure

### PR DESCRIPTION
**Pull request by lfrancke**
## Description

This is just an initial PR to get started with a function I need for a rudimentary UI

## Review Checklist
- [x] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [x] Documentation added (or not applicable)
- [x] Changelog updated (or not applicable)

### CODE REVIEW

**Review by sbernauer — APPROVED** [review]
Tested using
```
use kube::Client;
use stackable_lib::StackableApi;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = Client::try_default().await?;

    let api = StackableApi::new(client);
    let crds = api.get_installed_stackable_crds().await?;
    dbg!(crds);

    Ok(())
}

```

**Comment by lfrancke** [comment]
Do you have any recommendations on how to add tests for this? I'm out of the loop....

**Comment by sbernauer** [comment]
I had the same question for myself. Guess it's pretty hard to mock the k8s apiserver. Would hand that question to @nightkr :see_no_evil: 
But I'm also fine with the current state

**Comment by lfrancke** [comment]
Maybe this is what https://kubernetes.io/blog/2023/03/01/introducing-kwok/ can be used for

**Pull request merged**
